#!/usr/bin/env ruby
# frozen_string_literal: true

require "station"

env_var_station_connection_protocol = "MARITIMO_STATION_CONNECTION_PROTOCOL"
env_var_station_connection_listen_port = "MARITIMO_STATION_CONNECTION_LISTEN_PORT"
env_var_station_hostname = "MARITIMO_STATION_HOSTNAME"
env_var_station_port = "MARITIMO_STATION_PORT"
env_var_station_read_timeout_seconds = "MARITIMO_STATION_READ_TIMEOUT_SECONDS"
env_var_broker_uri = "MARITIMO_RABBITMQ_URI"
env_var_queue_name = "MARITIMO_RABBITMQ_ENCODED_MESSAGES_QUEUE_NAME"
env_var_include_sender_ip = "MARITIMO_STATION_INCLUDE_SENDER_IP_ADDRESS"

station_connection_protocol = ENV[env_var_station_connection_protocol]
station_connection_listen_port = ENV[env_var_station_connection_listen_port]
station_hostname = ENV[env_var_station_hostname]
station_port = ENV[env_var_station_port]
station_read_timeout_seconds = ENV[env_var_station_read_timeout_seconds]
broker_uri = ENV[env_var_broker_uri]
queue_name = ENV[env_var_queue_name]
include_sender_ip = ENV[env_var_include_sender_ip]

unless station_connection_protocol
  warn "No station connection protocol configured. Set #{env_var_station_connection_protocol} environment variable"

  return
end

if station_connection_protocol == "TCP"
  unless station_hostname
    warn "No station hostname configured. Set #{env_var_station_hostname} environment variable"

    return
  end

  unless station_port
    warn "No station port configured. Set #{env_var_station_port} environment variable"

    return
  end

  unless station_read_timeout_seconds
    warn "No station read timeout value configured. Set #{env_var_station_read_timeout_seconds} environment variable"

    return
  end
elsif station_connection_protocol == "UDP"
  unless station_connection_listen_port
    warn "No connection listen port configured. Set #{env_var_station_connection_listen_port} environment variable"

    return
  end
else
  warn "Unsupported connection protocol: #{station_connection_protocol}"

  return
end

unless broker_uri
  warn "No broker URI configured. Set #{env_var_broker_uri} environment variable"

  return
end

unless queue_name
  warn "No queue name configured. Set #{env_var_queue_name} environment variable"

  return
end

unless include_sender_ip
  warn "Inclusion of sender's ip address is not configured. Set #{env_var_include_sender_ip} environment variable"

  return
end

include_sender_ip = include_sender_ip.downcase
include_sender_ip = include_sender_ip == "true" || include_sender_ip == "t" || include_sender_ip == "1"

if station_connection_protocol == "TCP"
  Station.application.run station_hostname, station_port, broker_uri, queue_name, station_read_timeout_seconds.to_i, include_sender_ip
elsif station_connection_protocol == "UDP"
  Station.udp_application.run station_connection_listen_port, broker_uri, queue_name, include_sender_ip
end
